//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarnishedTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TarnishedTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200100,Aspects of the Crucible: Wings,cf00,ff8306008006
        ///60200,Assassin&apos;s Gambit,0f1c,c30100008002
        ///65000,Barbaric Roar,ff1f,fefcbe00100e
        ///40100,Barrage,0100,000000010000
        ///30100,Barricade Shield,ff1f,000000004700
        ///65200,Beast&apos;s Roar,ff1f,fffffe00f00f
        ///22100,Black Flame Tornado,3f00,80800e000000
        ///409000,Blind Spot,ff1f,000000000001
        ///413000,Blinkbolt,cf00,fffffe00d00f
        ///22400,Blood Blade,0f1c,d30100008003
        ///10800,Blood Tax,0f1c,c7830600c006
        ///80100,Bloodhound&apos;s Step,ff1f,fffffe00f00f
        ///20400,Bloody Slash,0f1c,f70 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AoW {
            get {
                return ResourceManager.GetString("AoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71190
        ///76101
        ///76100
        ///76111
        ///76104
        ///76105
        ///76102
        ///71002
        ///76117
        ///71007
        ///71006
        ///76201
        ///76216
        ///76205
        ///76213
        ///76214
        ///76230
        ///76228
        ///76208
        ///76209
        ///76239
        ///76401
        ///76417
        ///76418
        ///76453
        ///76451
        ///76301
        ///76309
        ///76312
        ///71104
        ///71105
        ///71107
        ///73501
        ///76500
        ///76502
        ///76501
        ///76504
        ///76521
        ///76508
        ///76510
        ///76550
        ///76551
        ///76652
        ///71506
        ///71507
        ///71508
        ///71501
        ///71504
        ///71253
        ///71271
        ///71224
        ///71225
        ///71234
        ///71235
        ///71216
        ///71218
        ///71306
        ///71309
        ///71310
        ///.
        /// </summary>
        internal static string ArBaseGraces {
            get {
                return ResourceManager.GetString("ArBaseGraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76800
        ///76802
        ///76813
        ///76810
        ///76812
        ///76803
        ///74301
        ///76852
        ///76822
        ///72003
        ///72013
        ///72014
        ///72015
        ///72016
        ///76941
        ///76943
        ///76902
        ///76900
        ///76906
        ///76905
        ///76918
        ///74002
        ///72106
        ///72107
        ///72109
        ///76931
        ///72111
        ///72114
        ///72116
        ///72117
        ///72120
        ///76935
        ///76835
        ///76834
        ///72202
        ///72203
        ///72204
        ///76862
        ///72801
        ///72803.
        /// </summary>
        internal static string ArDlcGraces {
            get {
                return ResourceManager.GetString("ArDlcGraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1001D588,Alberich&apos;s Bracers,1,1
        ///0,1001D4C0,Alberich&apos;s Pointed Hat,1,1
        ///0,1001D8A8,Alberich&apos;s Pointed Hat (Altered),1,1
        ///0,1001D524,Alberich&apos;s Robe,1,1
        ///0,1001D90C,Alberich&apos;s Robe (Altered),1,1
        ///0,1001D5EC,Alberich&apos;s Trousers,1,1
        ///0,10102CA0,Albinauric Mask,1,1
        ///0,10090114,All-Knowing Armor,1,1
        ///0,100904FC,All-Knowing Armor (Altered),1,1
        ///0,10090178,All-Knowing Gauntlets,1,1
        ///0,100901DC,All-Knowing Greaves,1,1
        ///0,100900B0,All-Knowing Helm,1,1
        ///0,104DF954,Ansbach&apos;s Attire,1,1
        ///0,104DFD3C,Ansbach&apos;s Attire ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,02faf080,Arrow,99,600
        ///0,02fb1790,Fire Arrow,99,600
        ///0,02fb3ea0,Serpent Arrow,99,600
        ///0,02fb65b0,Bone Arrow (Fletched),99,600
        ///0,02fb8cc0,St. Trina&apos;s Arrow,99,600
        ///0,02fbdae0,Shattershard Arrow (Fletched),99,600
        ///0,02fc2900,Rainbow Stone Arrow (Fletched),99,600
        ///0,02fc5010,Golden Arrow,99,600
        ///0,02fc7720,Dwelling Arrow,99,600
        ///0,02fc9e30,Bone Arrow,99,600
        ///0,02fcec50,Firebone Arrow (Fletched),99,600
        ///0,02fd1360,Firebone Arrow,99,600
        ///0,02fd3a70,Poisonbone Arrow (Fletched),99,600
        ///0,02fd6180,Poisonbone Arr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arrows {
            get {
                return ResourceManager.GetString("Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,80030DA4,Aspects of the Crucible: Wings,1,0
        ///0,8000EB28,Assassin&apos;s Gambit,1,0
        ///0,8000FDE8,Barbaric Roar,1,0
        ///0,80009CA4,Barrage,1,0
        ///0,80007594,Barricade Shield,1,0
        ///0,8000FEB0,Beast&apos;s Roar,1,0
        ///0,80005654,Black Flame Tornado,1,0
        ///0,80063DA8,Blind Spot,1,0
        ///0,80064D48,Blinkbolt,1,0
        ///0,80005780,Blood Blade,1,0
        ///0,80002A30,Blood Tax,1,0
        ///0,800138E4,Bloodhound&apos;s Step,1,0
        ///0,80004FB0,Bloody Slash,1,0
        ///0,8000FF78,Braggart&apos;s Roar,1,0
        ///0,80005528,Carian Grandeur,1,0
        ///0,8000558C,Carian Greatsword,1,0
        ///0,80007724, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AshOfWarSpawn {
            get {
                return ResourceManager.GetString("AshOfWarSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62004
        ///62005
        ///62006
        ///62007
        ///62008
        ///62009
        ///62010
        ///62011
        ///62012
        ///62022
        ///62021
        ///62020
        ///62031
        ///62030
        ///62032
        ///62041
        ///62040
        ///62052
        ///62051
        ///62050
        ///62063
        ///62062
        ///62061
        ///62060
        ///62064
        ///62103
        ///62102
        ///82001
        ///.
        /// </summary>
        internal static string BaseGameMaps {
            get {
                return ResourceManager.GetString("BaseGameMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///20
        ///21
        ///22
        ///23
        ///24
        ///25
        ///30
        ///40
        ///41
        ///50
        ///51
        ///52
        ///53
        ///54
        ///60
        ///70
        ///71
        ///72
        ///73
        ///80
        ///90
        ///91
        ///92
        ///93
        ///94
        ///95
        ///97
        ///98
        ///100
        ///101
        ///102
        ///103
        ///104
        ///105
        ///106
        ///.
        /// </summary>
        internal static string BaseGestures {
            get {
                return ResourceManager.GetString("BaseGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,400022E9,Abandoned Merchant&apos;s Bell Bearing,1,1
        ///0,400022D4,Bernahl&apos;s Bell Bearing,1,1
        ///0,400022EE,Blackguard&apos;s Bell Bearing,1,1
        ///0,400022F1,Bone Peddler&apos;s Bell Bearing,1,1
        ///0,400022EF,Corhyn&apos;s Bell Bearing,1,1
        ///0,400022D3,D&apos;s Bell Bearing,1,1
        ///0,40002303,Ghost-Glovewort Picker&apos;s Bell Bearing [1],1,1
        ///0,40002304,Ghost-Glovewort Picker&apos;s Bell Bearing [2],1,1
        ///0,40002305,Ghost-Glovewort Picker&apos;s Bell Bearing [3],1,1
        ///0,40002300,Glovewort Picker&apos;s Bell Bearing [1],1,1
        ///0,40002301,Glovewort Picker&apos;s Bell Beari [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BellBearings {
            get {
                return ResourceManager.GetString("BellBearings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALSE,Limgrave,Beastman of Farum Azula,FALSE,39701910,520290304,31030801:FALSE,31030800:FALSE|9233:FALSE|520330:FALSE|31035014:FALSE,-94.56|89.93|63.94|1,2.5,-94.56|89.93|63.94|1,2.5,FALSE,520290304
        ///FALSE,Limgrave,Bell Bearing Hunter,TRUE,31000033,1009395200,,1042380850:FALSE|1042387410:FALSE,-2.71|188.32|102.02|1,-0.87,-2.71|188.32|102.02|1,-0.87,TRUE,1009395200
        ///FALSE,Limgrave,Black Knife Assassin,FALSE,21000820,504037376,,30110800:FALSE|9203:FALSE|520030:FALSE,-171.94|177.79|23.30|1,1.47,-171.94|177.79| [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BossRevives {
            get {
                return ResourceManager.GetString("BossRevives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Limgrave,Beastman of Farum Azula,520290304,-94.56|89.93|63.94|1,2.5
        ///0,Limgrave,Bell Bearing Hunter,1009395200,-2.71|188.32|102.02|1,-0.87
        ///0,Limgrave,Black Knife Assassin,504037376,-171.94|177.79|23.30|1,1.47
        ///0,Limgrave,Bloodhound Knight Darriwil,1009525504,-15.51|104.36|-112.79|1,0.8
        ///0,Limgrave,Crucible Knight,1009394944,-68.52|158.16|45.94|1,-0.83
        ///0,Limgrave,Crystalian,537001984,23.46|112.06|-3.61|1,3.13
        ///0,Limgrave,Deathbird,1009395200,90.76|199.90|95.32|1,-0.63
        ///0,Limgrave,Demi-Human Chiefs,521076 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BossWarps {
            get {
                return ResourceManager.GetString("BossWarps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,401E8CB4,Ancient Dragon&apos;s Blessing,1,0
        ///0,40000D20,Baldachin&apos;s Blessing,1,0
        ///0,40000D16,Bewitching Branch,10,600
        ///0,401E8804,Blessing of Marika,1,600
        ///0,400005A0,Blood Grease,10,600
        ///0,40000334,Boiled Crab,99,600
        ///0,4000033E,Boiled Prawn,10,600
        ///0,401E9038,Bondstone,1,600
        ///0,400006AE,Bone Dart,40,600
        ///1,401E9007,Broken Rune,99,600
        ///0,401E90CE,Call of Tibia,10,600
        ///0,401E9196,Charming Branch,10,600
        ///0,400003C0,Clarifying Boluses,99,600
        ///0,4000046A,Clarifying Cured Meat,10,999
        ///0,40000532,Clarifying White C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Consumables {
            get {
                return ResourceManager.GetString("Consumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40002134,Crafting Kit,1,1,1,60120
        ///0,400024B8,Ancient Dragon Apostle&apos;s Cookbook [1],1,1,1,68000
        ///0,400024B9,Ancient Dragon Apostle&apos;s Cookbook [2],1,1,1,68010
        ///0,400024BB,Ancient Dragon Apostle&apos;s Cookbook [3],1,1,1,68030
        ///0,400024BA,Ancient Dragon Apostle&apos;s Cookbook [4],1,1,1,68020
        ///1,401EA8EC,Ancient Dragon Knight&apos;s Cookbook [1],1,1,1,68740
        ///1,401EA8F0,Ancient Dragon Knight&apos;s Cookbook [2],1,1,1,68780
        ///1,401EA8FD,Antiquity Scholar&apos;s Cookbook [1],1,1,1,68910
        ///1,401EA8F8,Antiquity Scholar&apos;s Cookbook [2],1,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cookbooks {
            get {
                return ResourceManager.GetString("Cookbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40005141,Aeonian Butterfly,999,999
        ///0,40003c3c,Albinauric Bloodclot,999,999
        ///0,400050c9,Altus Bloom,999,999
        ///0,400050d3,Arteria Leaf,999,999
        ///0,40003ab6,Beast Blood,999,999
        ///1,401ebf18,Beast Horn,999,999
        ///0,40003aa2,Beast Liver,999,999
        ///1,401ed2a6,Black Pyrefly,999,999
        ///1,401ed2bf,Blessed Bone Shard,999,999
        ///0,4000515f,Blood-Tainted Excrement,999,999
        ///0,400050f3,Bloodrose,999,999
        ///0,40005169,Budding Cave Moss,999,999
        ///0,40003aca,Budding Horn,999,999
        ///0,40005168,Cave Moss,999,999
        ///1,401ed2ba,Congealed Putr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CraftingMaterials {
            get {
                return ResourceManager.GetString("CraftingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 8d 08                lea    rcx,[rax]
        ///c7 04 24 fe fe fe fe    mov    DWORD PTR [rsp],0xfefefefe
        ///48 8d 14 24             lea    rdx,[rsp]
        ///41 b8 fe fe fe fe       mov    r8d,0xfefefefe
        ///49 b9 00 00 00 00 00    movabs r9,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string CreateNpcTalk {
            get {
                return ResourceManager.GetString("CreateNpcTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,401eafaa,Bloodsucking Cracked Tear,1,1
        ///0,40002afc,Cerulean Crystal Tear,1,1
        ///0,40002afd,Cerulean Crystal Tear,1,1
        ///0,40002b11,Cerulean Hidden Tear,1,1
        ///1,401eaf96,Cerulean-Sapping Cracked Tear,1,1
        ///0,40002aff,Crimson Bubbletear,1,1
        ///0,40002afa,Crimson Crystal Tear,1,1
        ///0,40002afb,Crimson Crystal Tear,1,1
        ///1,401eaf8c,Crimson-Sapping Cracked Tear,1,1
        ///0,40002b01,Crimsonburst Crystal Tear,1,1
        ///1,401eaf82,Crimsonburst Dried Tear,1,1
        ///0,40002af8,Crimsonspill Crystal Tear,1,1
        ///0,40002b0c,Crimsonwhorl Bubbletea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CrystalTears {
            get {
                return ResourceManager.GetString("CrystalTears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 41 10             mov    rax,QWORD PTR [rcx+0x10]
        ///48 3b 05 00 00 00 00    cmp    rax,QWORD PTR [rip+0x0]        # c &lt;_main+0xc&gt;
        ///75 0b                   jne    19 &lt;skip&gt;
        ///58                      pop    rax
        ///48 89 5c 24 08          mov    QWORD PTR [rsp+0x8],rbx
        ///e9 00 00 00 00          jmp    19 &lt;skip&gt;
        ///000000000019 &lt;skip&gt;:
        ///58                      pop    rax
        ///30 c0                   xor    al,al
        ///c3                      ret.
        /// </summary>
        internal static string DisableAllExceptTarget {
            get {
                return ResourceManager.GetString("DisableAllExceptTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111
        ///112
        ///113
        ///114
        ///115
        ///116.
        /// </summary>
        internal static string DlcGestures {
            get {
                return ResourceManager.GetString("DlcGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62080
        ///62081
        ///62082
        ///62083
        ///62084
        ///82002.
        /// </summary>
        internal static string DLCMaps {
            get {
                return ResourceManager.GetString("DLCMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Nebula Hand Slam
        ///3,Spin Swing
        ///4,Straight Nebula
        ///5,Single Poke
        ///6,5 Hit Combo
        ///7,Wave of Gold
        ///8,Fire Breath
        ///10,Grab
        ///11,Swim Left Attack
        ///12,Swim Right Attack
        ///14,Standing Needles
        ///15,Stake Attack
        ///19,Fly Attack
        ///20,Nebula Swipe
        ///21,Nebula AoE
        ///30,Swim Needles
        ///31,Flying Needles.
        /// </summary>
        internal static string EbActs {
            get {
                return ResourceManager.GetString("EbActs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 5c 24 08          mov    QWORD PTR [rsp+0x8],rbx
        ///50                      push   rax
        ///53                      push   rbx
        ///57                      push   rdi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///89 f8                   mov    eax,edi
        ///6b c0 05                imul   eax,eax,0x5
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # 1a &lt;_main+0x1a&gt;
        ///48 01 c3                add    rbx,rax
        ///89 13                   mov    DWORD PTR [rbx],edx
        ///44 88 43 04            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventLogHook {
            get {
                return ResourceManager.GetString("EventLogHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 e5                mov    rbp,rsp
        ///48 81 ec 08 04 00 00    sub    rsp,0x408
        ///48 8d 8d 50 fe ff ff    lea    rcx,[rbp-0x1b0]
        ///48 8d 95 40 fe ff ff    lea    rdx,[rbp-0x1c0]
        ///c7 02 00 00 00 00       mov    DWORD PTR [rdx],0x0
        ///66 c7 42 04 ff ff       mov    WORD PTR [rdx+0x4],0xffff
        ///c7 42 08 00 00 00 00    mov    DWORD PTR [rdx+0x8],0x0
        ///4c 8d 85 30 fe ff ff    lea    r8,[rbp-0x1d0]
        ///49 c7 00 00 00 00 00    mov    QWORD PTR [r8],0x0
        ///49 c7 40 08 00 00 00    mov    QWORD PTR [r8+0x8],0x0
        ///00
        ///4c 8d 8d 20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExecuteEmevdCommand {
            get {
                return ResourceManager.GetString("ExecuteEmevdCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 81 ec 98 04 00 00    sub    rsp,0x498
        ///41 b9 fe fe fe fe       mov    r9d,0xfefefefe
        ///45 89 c8                mov    r8d,r9d
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///41 c1 e0 04             shl    r8d,0x4
        ///4a 8d 0c 00             lea    rcx,[rax+r8*1]
        ///48 89 8c 24 80 04 00    mov    QWORD PTR [rsp+0x480],rcx
        ///00
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 10                mov    rdx,QWORD PTR [rax]
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///4c 8d 04 24             lea   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExecuteEnvQuery {
            get {
                return ResourceManager.GetString("ExecuteEnvQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 e5                mov    rbp,rsp
        ///48 81 ec 98 05 00 00    sub    rsp,0x598
        ///48 8d 8d e0 fb ff ff    lea    rcx,[rbp-0x420]
        ///ba 00 00 00 00          mov    edx,0x0
        ///e8 00 00 00 00          call   1b &lt;_main+0x1b&gt;
        ///48 8d 8d c8 fb ff ff    lea    rcx,[rbp-0x438]
        ///48 8d 95 c8 fa ff ff    lea    rdx,[rbp-0x538]
        ///48 89 51 10             mov    QWORD PTR [rcx+0x10],rdx
        ///4c 8d 85 a8 fa ff ff    lea    r8,[rbp-0x558]
        ///4c 89 82 98 00 00 00    mov    QWORD PTR [rdx+0x98],r8
        ///49 89 50 18             mov    QWORD P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExecuteTalkCommand {
            get {
                return ResourceManager.GetString("ExecuteTalkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 7 &lt;_main+0x7&gt;
        ///75 39                   jne    42 &lt;normal&gt;
        ///81 78 28 00 00 00 00    cmp    DWORD PTR [rax+0x28],0x0
        ///75 30                   jne    42 &lt;normal&gt;
        ///52                      push   rdx
        ///41 50                   push   r8
        ///8b 15 00 00 00 00       mov    edx,DWORD PTR [rip+0x0]        # 1b &lt;_main+0x1b&gt;
        ///4c 8d 05 00 00 00 00    lea    r8,[rip+0x0]        # 22 &lt;_main+0x22&gt;
        ///41 8b 04 90             mov    eax,DWORD PTR [r8+rdx*4]
        ///ff c2      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForceActSequence {
            get {
                return ResourceManager.GetString("ForceActSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49 c7 c1 04 00 00 00    mov    r9,0x4
        ///41 b8 cd 00 00 00       mov    r8d,0xcd
        ///e9 00 00 00 00          jmp    12 &lt;_main+0x12&gt;.
        /// </summary>
        internal static string ForceLoadScreenMidPatches {
            get {
                return ResourceManager.GetString("ForceLoadScreenMidPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49 c7 c1 04 00 00 00    mov    r9,0x4
        ///31 d2                   xor    edx,edx
        ///e9 00 00 00 00          jmp    e &lt;_main+0xe&gt;.
        /// </summary>
        internal static string ForceLoadScreenReminder {
            get {
                return ResourceManager.GetString("ForceLoadScreenReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49 c7 c0 04 00 00 00    mov    r8,0x4
        ///ba cd 00 00 00          mov    edx,0xcd
        ///e9 00 00 00 00          jmp    11 &lt;_main+0x11&gt;.
        /// </summary>
        internal static string ForceLoadScreenReminderEarlyPatches {
            get {
                return ResourceManager.GetString("ForceLoadScreenReminderEarlyPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///48 8d 54 24 24          lea    rdx,[rsp+0x24]
        ///c7 02 fe fe fe fe       mov    DWORD PTR [rdx],0xfefefefe
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 89 01                mov    QWORD PTR [rcx],rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string GetChrIns {
            get {
                return ResourceManager.GetString("GetChrIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///88 01                   mov    BYTE PTR [rcx],al
        ///c3                      ret.
        /// </summary>
        internal static string GetEvent {
            get {
                return ResourceManager.GetString("GetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string GiveRunes {
            get {
                return ResourceManager.GetString("GiveRunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Roundtable Hold,Table of Lost Grace,11101950,71190
        ///0,Limgrave,The First Step,1042361951,76101
        ///0,Limgrave,Church of Elleh,1042361950,76100
        ///0,Limgrave,Gatefront,1042371950,76111
        ///0,Limgrave,Waypoint Ruins Cellar,1044361950,76120
        ///0,Limgrave,Artist&apos;s Shack,1044381950,76103
        ///0,Limgrave,Third Church of Marika,1046381950,76104
        ///0,Limgrave,Fort Haight West,1045361950,76105
        ///0,Limgrave,Agheel Lake South,1044351950,76106
        ///0,Limgrave,Agheel Lake North,1043371950,76108
        ///0,Limgrave,Church of Dragon Communion,10413 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Graces {
            get {
                return ResourceManager.GetString("Graces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 48 18             mov    rcx,QWORD PTR [rax+0x18]
        ///48 8b 50 08             mov    rdx,QWORD PTR [rax+0x8]
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string GraceWarp {
            get {
                return ResourceManager.GetString("GraceWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40001B59,Agheel&apos;s Flame,99,600
        ///0,40001B1C,Ancient Dragons&apos; Lightning Spear,99,600
        ///0,40001AFE,Ancient Dragons&apos; Lightning Strike,99,600
        ///1,401E9E84,Aspects of the Crucible: Bloom,99,600
        ///0,40001D60,Aspects of the Crucible: Breath,99,600
        ///0,40001D56,Aspects of the Crucible: Horns,99,600
        ///0,40001D4C,Aspects of the Crucible: Tail,99,600
        ///1,401E9E7A,Aspects of the Crucible: Thorns,99,600
        ///0,4000196E,Assassin&apos;s Approach,99,600
        ///0,400018BA,Barrier of Gold,99,600
        ///1,401E9FE2,Bayle&apos;s Flame Lightning,99,600
        ///1,401 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Incantations {
            get {
                return ResourceManager.GetString("Incantations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49 89 f8                mov    r8,rdi
        ///40 0f b6 d5             movzx  edx,bpl
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # f &lt;_main+0xf&gt;
        ///48 3b 88 08 e5 01 00    cmp    rcx,QWORD PTR [rax+0x1e508]
        ///74 4f                   je     67 &lt;invalidatePoise&gt;
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 8b 80 e8 00 00 00    mov    rax,QWORD PTR [rax+0xe8]
        ///48 8b 40 10             mov    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfinitePoise {
            get {
                return ResourceManager.GetString("InfinitePoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # b &lt;_main+0xb&gt;
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 12 &lt;_main+0x12&gt;
        ///74 1d                   je     31 &lt;skip_quantity_adjust&gt;
        ///48 8d 4b 44             lea    rcx,[rbx+0x44]
        ///e8 00 00 00 00          call   1d &lt;_main+0x1d&gt;
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # 23 &lt;_main+0x23&gt;
        ///8b 53 48                mov    edx,DWORD PTR [rbx+0x48]
        ///01 c2                   add     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemSpawn {
            get {
                return ResourceManager.GetString("ItemSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40001FAD,Academy Glintstone Key (Player),1,1,0,-1
        ///0,40001FEE,Academy Glintstone Key (Thops),1,1,0,-1
        ///0,400022A2,Academy Scroll,1,1,0,-1
        ///0,40001FE6,Amber Draught,1,1,0,-1
        ///0,40001FCE,Amber Starlight,1,1,0,-1
        ///0,40000BB8,Ancestral Infant&apos;s Head,1,600,1,12027090
        ///0,400022A1,Ancient Dragon Prayerbook,1,1,0,-1
        ///1,401EA3DC,Ancient Ruins Cross Message,1,1,1,2047477000
        ///0,4000229B,Assassin&apos;s Prayerbook,1,1,0,-1
        ///0,40002313,Beast Eye,1,1,1,400239
        ///0,40001FEC,Black Knifeprint,1,1,0,-1
        ///1,401EA3D3,Black Syrup,1,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyItems {
            get {
                return ResourceManager.GetString("KeyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///49 be 00 00 00 00 00    movabs r14,0x0
        ///00 00 00
        ///49 bf 00 00 00 00 00    movabs r15,0x0
        ///00 00 00
        ///49 8b 8f 08 e5 01 00    mov    rcx,QWORD PTR [r15+0x1e508]
        ///48 8b 01                mov    rax,QWORD PTR [rcx]
        ///ff 10                   call   QWORD PTR [rax]
        ///48 89 c6                mov    rsi,rax
        ///49 8b bf b8 f1 01 00    mov    rdi,QWORD PTR [r15+0x1f1b8]
        ///49 8b 9f c0 f1 01 00    mov    rbx,QWORD PTR [r15+0x1f1c0]
        ///000000000035 &lt;loop_start&gt;:
        ///48 39 df                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KillAll {
            get {
                return ResourceManager.GetString("KillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 81 7e 60 f8 fb 1a    cmp    DWORD PTR [r14+0x60],0x31afbf8
        ///03
        ///75 22                   jne    2c &lt;exit&gt;
        ///49 81 fa d0 58 31 01    cmp    r10,0x13158d0
        ///75 09                   jne    1c &lt;check_other&gt;
        ///c7 41 08 00 00 80 bf    mov    DWORD PTR [rcx+0x8],0xbf800000
        ///eb 10                   jmp    2c &lt;exit&gt;
        ///00000000001c &lt;check_other&gt;:
        ///49 81 fa e5 58 31 01    cmp    r10,0x13158e5
        ///75 07                   jne    2c &lt;exit&gt;
        ///c7 41 08 00 00 80 bf    mov    DWORD PTR [rcx+0x8],0xbf800000
        ///00000000002c &lt;exit&gt;:
        ///f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LionCooldownHook {
            get {
                return ResourceManager.GetString("LionCooldownHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 8f 88 00 00 00    mov    rcx,QWORD PTR [rdi+0x88]
        ///48 89 05 00 00 00 00    mov    QWORD PTR [rip+0x0],rax        # e &lt;_main+0xe&gt;
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string LockedTarget {
            get {
                return ResourceManager.GetString("LockedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51                      push   rcx
        ///52                      push   rdx
        ///41 50                   push   r8
        ///41 51                   push   r9
        ///50                      push   rax
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///48 8b 54 24 70          mov    rdx,QWORD PTR [rsp+0x70]
        ///8b 52 18                mov    edx,DWORD PTR [rdx+0x18]
        ///41 b8 00 00 00 00       mov    r8d,0x0
        ///48 83 ec 20             sub    rsp,0x20
        ///e8 00 00 00 00          call   25 &lt;_main+0x25&gt;
        ///48 83 c4 20  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoAcquiredMapPopup {
            get {
                return ResourceManager.GetString("NoAcquiredMapPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 3b 58 70             cmp    rbx,QWORD PTR [rax+0x70]
        ///75 03                   jne    22 &lt;normal&gt;
        ///0f 57 c0                xorps  xmm0,xmm0
        ///000000000022 &lt;normal&gt;:
        ///f3 0f 11 43 18          movss  DWORD PTR [rbx+0x18],xmm0
        ///58                      pop    rax
        ///e9 00 00 00 00          jmp    2d &lt;normal+0x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_InAirTimer {
            get {
                return ResourceManager.GetString("NoClip_InAirTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83 fa 06                cmp    edx,0x6
        ///75 01                   jne    6 &lt;normal&gt;
        ///c3                      ret
        ///000000000006 &lt;normal&gt;:
        ///49 09 41 10             or     QWORD PTR [r9+0x10],rax
        ///c3                      ret.
        /// </summary>
        internal static string NoClip_JumpHook {
            get {
                return ResourceManager.GetString("NoClip_JumpHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 f8 39             cmp    rax,0x39
        ///75 13                   jne    19 &lt;check_ctrl&gt;
        ///f6 84 08 e8 07 00 00    test   BYTE PTR [rax+rcx*1+0x7e8],0x80
        ///80
        ///76 09                   jbe    19 &lt;check_ctrl&gt;
        ///c6 05 00 00 00 00 02    mov    BYTE PTR [rip+0x0],0x2        # 17 &lt;_main+0x17&gt;
        ///eb 17                   jmp    30 &lt;xor_exit&gt;
        ///000000000019 &lt;check_ctrl&gt;:
        ///48 83 f8 1d             cmp    rax,0x1d
        ///75 1a                   jne    39 &lt;normal&gt;
        ///f6 84 08 e8 07 00 00    test   BYTE PTR [rax+rcx*1+0x7e8],0x80
        ///80
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Keyboard {
            get {
                return ResourceManager.GetString("NoClip_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 7c 24 36 4b          cmp    BYTE PTR [rsp+0x36],0x4b
        ///72 0e                   jb     15 &lt;check_up&gt;
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # e &lt;_main+0xe&gt;
        ///c6 44 24 36 00          mov    BYTE PTR [rsp+0x36],0x0
        ///eb 13                   jmp    28 &lt;exit&gt;
        ///000000000015 &lt;check_up&gt;:
        ///80 7c 24 37 4b          cmp    BYTE PTR [rsp+0x37],0x4b
        ///72 0c                   jb     28 &lt;exit&gt;
        ///c6 05 00 00 00 00 02    mov    BYTE PTR [rip+0x0],0x2        # 23 &lt;check_up+0xe&gt;
        ///c6 44 24 37 00          mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Triggers {
            get {
                return ResourceManager.GetString("NoClip_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///51                      push   rcx
        ///41 51                   push   r9
        ///41 50                   push   r8
        ///52                      push   rdx
        ///57                      push   rdi
        ///48 8b 15 00 00 00 00    mov    rdx,QWORD PTR [rip+0x0]        # f &lt;_main+0xf&gt;
        ///48 8b 82 08 e5 01 00    mov    rax,QWORD PTR [rdx+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 3b 58 68             cmp    rbx,QWORD PTR [rax+0x68]
        ///74 3d                   je     60 &lt;start&gt;
        ///4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_UpdateCoords {
            get {
                return ResourceManager.GetString("NoClip_UpdateCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 3b 45 08             cmp    rax,QWORD PTR [rbp+0x8]
        ///58                      pop    rax
        ///0f 84 00 00 00 00       je     1a &lt;_main+0x1a&gt;
        ///41 8b 56 44             mov    edx,DWORD PTR [r14+0x44]
        ///48 8d 4c 24 40          lea    rcx,[rsp+0x40]
        ///e9 00 00 00 00          jmp    28 &lt;_main+0x28&gt;.
        /// </summary>
        internal static string NoGrab {
            get {
                return ResourceManager.GetString("NoGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51                      push   rcx
        ///48 8b 49 08             mov    rcx,QWORD PTR [rcx+0x8]
        ///48 3b 0d 00 00 00 00    cmp    rcx,QWORD PTR [rip+0x0]        
        ///75 06                   jne    14 &lt;normal&gt;
        ///8b 81 88 09 00 00       mov    eax,DWORD PTR [rcx+0x988]
        ///000000000014 &lt;normal&gt;:
        ///59                      pop    rcx
        ///89 81 38 01 00 00       mov    DWORD PTR [rcx+0x138],eax
        ///e9 00 00 00 00          jmp    20 &lt;normal+0xc&gt; .
        /// </summary>
        internal static string NoHeal {
            get {
                return ResourceManager.GetString("NoHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4c 8b 74 24 70          mov    r14,QWORD PTR [rsp+0x70]
        ///50                      push   rax
        ///51                      push   rcx
        ///52                      push   rdx
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # f &lt;_main+0xf&gt;
        ///48 8b 15 00 00 00 00    mov    rdx,QWORD PTR [rip+0x0]        # 16 &lt;_main+0x16&gt;
        ///48 8b 08                mov    rcx,QWORD PTR [rax]
        ///48 89 4a 20             mov    QWORD PTR [rdx+0x20],rcx
        ///48 8b 48 08             mov    rcx,QWORD PTR [rax+0x8]
        ///48 89 4a 28            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoTimePassOnDeath {
            get {
                return ResourceManager.GetString("NoTimePassOnDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40000295,Academy Magic Pot,10,600
        ///0,40000E1A,Acid Spraymist,10, 600
        ///0,40000262,Albinauric Pot,10,600
        ///0,40000186,Alluring Pot,10,600
        ///0,40000141,Ancient Dragonbolt Pot,10,600
        ///0,40000187,Beastlure Pot,10,600
        ///0,40000276,Cursed-Blood Pot,10,600
        ///1,401E8764,Eternal Sleep Pot,10,600
        ///0,4000014A,Fetid Pot,10,600
        ///0,4000012C,Fire Pot,10,600
        ///0,40000168,Freezing Pot,10,600
        ///1,401E8746,Frenzied Flame Pot,10,600
        ///0,4000012E,Giantsflame Fire Pot,10,600
        ///1,401E85CA,Hefty Fetid Pot,10,600
        ///1,401E85AC,Hefty Fire Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PotsAndPerfumes {
            get {
                return ResourceManager.GetString("PotsAndPerfumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,4000089A,Prattling Pate &quot;Apologies&quot;,1,600
        ///0,40000898,Prattling Pate &quot;Hello&quot;,1,600
        ///1,401E8CE6,Prattling Pate &quot;Lamentation&quot;,1,600
        ///0,4000089E,Prattling Pate &quot;Let&apos;s get to it&quot;,1,600
        ///0,4000089D,Prattling Pate &quot;My beloved&quot;,1,600
        ///0,4000089C,Prattling Pate &quot;Please help&quot;,1,600
        ///0,40000899,Prattling Pate &quot;Thank you&quot;,1,600
        ///0,4000089B,Prattling Pate &quot;Wonderful&quot;,1,600
        ///0,4000089F,Prattling Pate &quot;You&apos;re beautiful&quot;,1,600
        ///.
        /// </summary>
        internal static string PrattlingPate {
            get {
                return ResourceManager.GetString("PrattlingPate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///52                      push   rdx
        ///41 50                   push   r8
        ///41 51                   push   r9
        ///48 83 ec 70             sub    rsp,0x70
        ///0f 11 04 24             movups XMMWORD PTR [rsp],xmm0
        ///0f 11 4c 24 10          movups XMMWORD PTR [rsp+0x10],xmm1
        ///0f 11 54 24 20          movups XMMWORD PTR [rsp+0x20],xmm2
        ///0f 11 5c 24 30          movups XMMWORD PTR [rsp+0x30],xmm3
        ///0f 11 64 24 40          movups XMMWORD PTR [rsp+0x40],xmm4
        ///0f 11 6c 24 50          movups XMM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReduceTargetView {
            get {
                return ResourceManager.GetString("ReduceTargetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string RemoveSpEffect {
            get {
                return ResourceManager.GetString("RemoveSpEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 49 08             mov    rcx,QWORD PTR [rcx+0x8]
        ///81 fa a5 2e 00 00       cmp    edx,0x2ea5
        ///75 03                   jne    f &lt;normal&gt;
        ///48 31 c9                xor    rcx,rcx
        ///00000000000f &lt;normal&gt;:
        ///48 85 c9                test   rcx,rcx
        ///e9 00 00 00 00          jmp    17 &lt;normal+0x8&gt;.
        /// </summary>
        internal static string RykardNoMega {
            get {
                return ResourceManager.GetString("RykardNoMega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 db                   xor    bl,bl
        ///0f 57 ff                xorps  xmm7,xmm7
        ///52                      push   rdx
        ///48 8b 15 00 00 00 00    mov    rdx,QWORD PTR [rip+0x0]        # d &lt;_main+0xd&gt;
        ///48 3b 96 e0 01 00 00    cmp    rdx,QWORD PTR [rsi+0x1e0]
        ///0f 85 d0 00 00 00       jne    ea &lt;normal&gt;
        ///51                      push   rcx
        ///53                      push   rbx
        ///50                      push   rax
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 23 &lt;_main+0x23&gt;
        ///8b 05 00 00 00 00       mov    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaveAttackInfo {
            get {
                return ResourceManager.GetString("SaveAttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 20             sub    rsp,0x20
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string SetEvent {
            get {
                return ResourceManager.GetString("SetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string SetSpEffect {
            get {
                return ResourceManager.GetString("SetSpEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Bernahl,22,100075,100099
        ///0,Boggart,22,100150,100174
        ///0,Borther Corhyn,22,100350,100399
        ///0,D,22,100125,100149
        ///1,Dragon Communion - Bayle,135,102350,102351
        ///0,Dragon Communion - Caelid,135,101950,101974
        ///0,Dragon Communion - Limgrave,135,101975,101999
        ///0,Enia - Equipment,148,101500,101574
        ///0,Enia - Remembrances,111,101898,101949
        ///0,Gostoc,22,100000,100024
        ///0,Gowry Incantations,22,100185,100199
        ///0,Gowry Sorceries,22,100175,100184
        ///0,Hermit Merchant - Leyndell,22,100725,100749
        ///0,Iji,22,100225,100249
        ///0,Imp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shops {
            get {
                return ResourceManager.GetString("Shops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,4000114F,Adula&apos;s Moonblade,99,600
        ///0,400011F8,Ambush Shard,99,600
        ///0,40001389,Ancient Death Rancor,99,600
        ///1,401E96DC,Blades of Stone,99,600
        ///0,4000132E,Briars of Punishment,99,600
        ///0,40001324,Briars of Sin,99,600
        ///0,40000FF0,Cannon of Haima,99,600
        ///0,4000114E,Carian Greatsword,99,600
        ///0,400010CD,Carian Phalanx,99,600
        ///0,40001162,Carian Piercer,99,600
        ///0,40001220,Carian Retaliation,99,600
        ///0,40001158,Carian Slicer,99,600
        ///1,401EA17C,Cherishing Fingers,99,600
        ///0,40001271,Collapsing Stars,99,600
        ///0,40000FB5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sorceries {
            get {
                return ResourceManager.GetString("Sorceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40033838,Albinauric Ashes,1,600
        ///0,40033068,Ancestral Follower Ashes,1,600
        ///1,4021CC58,Ancient Dragon Florissax,1,600
        ///0,4003E800,Ancient Dragon Knight Kristoff,1,600
        ///0,4003CCA8,Archer Ashes,1,600
        ///0,400372D0,Avionette Soldier Ashes,1,600
        ///0,40038270,Azula Beastman Ashes,1,600
        ///0,40031510,Banished Knight Engvall,1,600
        ///0,40031128,Banished Knight Oleg,1,600
        ///0,40035F48,Battlemage Hugues,1,600
        ///1,4021B8D0,Bigmouth Imp Ashes,1,600
        ///0,40030D40,Black Knife Tiche,1,600
        ///1,4021B4E8,Black Knight Captain Huw,1,60 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpiritAshes {
            get {
                return ResourceManager.GetString("SpiritAshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,200003e8,Crimson Amber Medallion,1,1
        ///0,200003e9,Crimson Amber Medallion +1,1,1
        ///0,200003ea,Crimson Amber Medallion +2,1,1
        ///0,200003f2,Cerulean Amber Medallion,1,1
        ///0,200003f3,Cerulean Amber Medallion +1,1,1
        ///0,200003f4,Cerulean Amber Medallion +2,1,1
        ///0,200003fc,Viridian Amber Medallion,1,1
        ///0,200003fd,Viridian Amber Medallion +1,1,1
        ///0,200003fe,Viridian Amber Medallion +2,1,1
        ///0,20000406,Arsenal Charm,1,1
        ///0,20000407,Arsenal Charm +1,1,1
        ///0,20000408,Great-Jar&apos;s Arsenal,1,1
        ///0,20000410,Erdtree&apos;s Favor,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Talismans {
            get {
                return ResourceManager.GetString("Talismans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 41 08             mov    rax,QWORD PTR [rcx+0x8]
        ///51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # c &lt;_main+0xc&gt;
        ///48 3b 48 08             cmp    rcx,QWORD PTR [rax+0x8]
        ///74 04                   je     16 &lt;skip&gt;
        ///83 48 2c 08             or     DWORD PTR [rax+0x2c],0x8
        ///000000000016 &lt;skip&gt;:
        ///59                      pop    rcx
        ///e9 00 00 00 00          jmp    1c &lt;skip+0x6&gt;.
        /// </summary>
        internal static string TargetNoStagger {
            get {
                return ResourceManager.GetString("TargetNoStagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40002774,Smithing Stone [1],999,999
        ///0,40002775,Smithing Stone [2],999,999
        ///0,40002776,Smithing Stone [3],999,999
        ///0,40002777,Smithing Stone [4],999,999
        ///0,40002778,Smithing Stone [5],999,999
        ///0,40002779,Smithing Stone [6],999,999
        ///0,4000277A,Smithing Stone [7],999,999
        ///0,4000277B,Smithing Stone [8],999,999
        ///0,4000279C,Ancient Dragon Smithing Stone,999,999
        ///0,400027B0,Somber Smithing Stone [1],999,999
        ///0,400027B1,Somber Smithing Stone [2],999,999
        ///0,400027B2,Somber Smithing Stone [3],999,999
        ///0,400027B3,S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpgradeMaterials {
            get {
                return ResourceManager.GetString("UpgradeMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 10 05 00 00 00 00    movups xmm0,XMMWORD PTR [rip+0x0]        # 7 &lt;_main+0x7&gt;
        ///0f 11 80 a0 0a 00 00    movups XMMWORD PTR [rax+0xaa0],xmm0
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string WarpCoordWrite {
            get {
                return ResourceManager.GetString("WarpCoordWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b9 ff ff ff ff          mov    ecx,0xffffffff
        ///ba ff ff ff ff          mov    edx,0xffffffff
        ///41 b8 ff ff ff ff       mov    r8d,0xffffffff
        ///41 b9 ff ff ff ff       mov    r9d,0xffffffff
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string WarpToBlock {
            get {
                return ResourceManager.GetString("WarpToBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33200000,Academy Glintstone Staff,57,2,0
        ///3070000,Alabaster Lord&apos;s Sword,5,0,1
        ///41010000,Albinauric Bow,51,2,0
        ///31040000,Albinauric Shield,67,2,0
        ///33190000,Albinauric Staff,57,2,0
        ///4500000,Ancient Meteoric Ore Greatsword,7,0,1
        ///41510000,Ansbach&apos;s Longbow,51,0,1
        ///32220000,Ant&apos;s Skull Plate,69,0,1
        ///5040000,Antspur Rapier,15,2,0
        ///12510000,Anvil Hammer,41,0,1
        ///43080000,Arbalest,55,0,0
        ///33130000,Astrologer&apos;s Staff,57,2,0
        ///23050000,Axe of Godfrey,41,0,1
        ///15040000,Axe of Godrick,19,0,1
        ///33230000,Azur&apos;s Glintstone  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Default
        ///1,Rainy
        ///2,Snowy
        ///3,Windy rain
        ///4,Foggy
        ///6,Flat clouds
        ///12,Windy puffy clouds
        ///15,Rainy heavy fog
        ///17,Scattered rain.
        /// </summary>
        internal static string WeatherTypes {
            get {
                return ResourceManager.GetString("WeatherTypes", resourceCulture);
            }
        }
    }
}
