//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilkyRing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilkyRing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200100,Aspects of the Crucible: Wings,cf00,ff8306008006
        ///60200,Assassin&apos;s Gambit,0f1c,c30100008002
        ///65000,Barbaric Roar,ff1f,fefcbe00100e
        ///40100,Barrage,0100,000000010000
        ///30100,Barricade Shield,ff1f,000000004700
        ///65200,Beast&apos;s Roar,ff1f,fffffe00f00f
        ///22100,Black Flame Tornado,3f00,80800e000000
        ///409000,Blind Spot,ff1f,000000000001
        ///413000,Blinkbolt,cf00,fffffe00d00f
        ///22400,Blood Blade,0f1c,d30100008003
        ///10800,Blood Tax,0f1c,c7830600c006
        ///80100,Bloodhound&apos;s Step,ff1f,fffffe00f00f
        ///20400,Bloody Slash,0f1c,f70 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AoW {
            get {
                return ResourceManager.GetString("AoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1001D588,Alberich&apos;s Bracers,1,1
        ///0,1001D4C0,Alberich&apos;s Pointed Hat,1,1
        ///0,1001D8A8,Alberich&apos;s Pointed Hat (Altered),1,1
        ///0,1001D524,Alberich&apos;s Robe,1,1
        ///0,1001D90C,Alberich&apos;s Robe (Altered),1,1
        ///0,1001D5EC,Alberich&apos;s Trousers,1,1
        ///0,10102CA0,Albinauric Mask,1,1
        ///0,10090114,All-Knowing Armor,1,1
        ///0,100904FC,All-Knowing Armor (Altered),1,1
        ///0,10090178,All-Knowing Gauntlets,1,1
        ///0,100901DC,All-Knowing Greaves,1,1
        ///0,100900B0,All-Knowing Helm,1,1
        ///0,104DF954,Ansbach&apos;s Attire,1,1
        ///0,104DFD3C,Ansbach&apos;s Attire ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,02faf080,Arrow,99,600
        ///0,02fb1790,Fire Arrow,99,600
        ///0,02fb3ea0,Serpent Arrow,99,600
        ///0,02fb65b0,Bone Arrow (Fletched),99,600
        ///0,02fb8cc0,St. Trina&apos;s Arrow,99,600
        ///0,02fbdae0,Shattershard Arrow (Fletched),99,600
        ///0,02fc2900,Rainbow Stone Arrow (Fletched),99,600
        ///0,02fc5010,Golden Arrow,99,600
        ///0,02fc7720,Dwelling Arrow,99,600
        ///0,02fc9e30,Bone Arrow,99,600
        ///0,02fcec50,Firebone Arrow (Fletched),99,600
        ///0,02fd1360,Firebone Arrow,99,600
        ///0,02fd3a70,Poisonbone Arrow (Fletched),99,600
        ///0,02fd6180,Poisonbone Arr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arrows {
            get {
                return ResourceManager.GetString("Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,400022E9,Abandoned Merchant&apos;s Bell Bearing,1,1
        ///0,400022D4,Bernahl&apos;s Bell Bearing,1,1
        ///0,400022EE,Blackguard&apos;s Bell Bearing,1,1
        ///0,400022F1,Bone Peddler&apos;s Bell Bearing,1,1
        ///0,400022EF,Corhyn&apos;s Bell Bearing,1,1
        ///0,400022D3,D&apos;s Bell Bearing,1,1
        ///0,40002303,Ghost-Glovewort Picker&apos;s Bell Bearing [1],1,1
        ///0,40002304,Ghost-Glovewort Picker&apos;s Bell Bearing [2],1,1
        ///0,40002305,Ghost-Glovewort Picker&apos;s Bell Bearing [3],1,1
        ///0,40002300,Glovewort Picker&apos;s Bell Bearing [1],1,1
        ///0,40002301,Glovewort Picker&apos;s Bell Beari [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BellBearings {
            get {
                return ResourceManager.GetString("BellBearings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Limgrave,Beast of Farum Azula,520290304,-94.56|89.93|63.94|1,2.50
        ///0,Limgrave,Bell Bearing Hunter,1009395200,-2.71|188.32|102.02|1,-0.87
        ///0,Limgrave,Black Knife Assassin,504037376,-171.94|177.79|23.30|1,1.47
        ///0,Limgrave,Bloodhound Knight Darriwil,1009525504,-15.51|104.36|-112.79|1,0.80
        ///0,Limgrave,Crucible Knight,1009394944,-68.52|158.16|45.94|1,-0.83
        ///0,Limgrave,Deathbird,1009395200,90.76|199.90|95.32|1,-0.63
        ///0,Limgrave,Demi-Human Chief,521076736,20.10|-26.18|-72.41|1,-0.02
        ///0,Limgrave,Erdtree Burial Wa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BossWarps {
            get {
                return ResourceManager.GetString("BossWarps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40000D16,Bewitching Branch,10,600
        ///0,401E8804,Blessing of Marika,1,600
        ///0,400005A0,Blood Grease,10,600
        ///0,40000334,Boiled Crab,99,600
        ///0,401E9038,Bondstone,1,600
        ///0,400006AE,Bone Dart,40,600
        ///0,401E90CE,Call of Tibia,10,600
        ///0,401E9196,Charming Branch,10,600
        ///0,400003C0,Clarifying Boluses,99,600
        ///0,4000046A,Clarifying Cured Meat,10,999
        ///0,40000532,Clarifying White Cured Meat,10,999
        ///0,400006CC,Crystal Dart,40,600
        ///0,40000BD6,Cuckoo Glintstone,10,600
        ///0,40000474,Dappled Cured Meat,10,999
        ///0,4000053C,Dapple [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Consumables {
            get {
                return ResourceManager.GetString("Consumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40002134,Crafting Kit,1,1,60120
        ///0,40002454,Nomadic Warrior&apos;s Cookbook [1],1,1,67000
        ///0,4000245F,Nomadic Warrior&apos;s Cookbook [2],1,1,67110
        ///0,40002455,Nomadic Warrior&apos;s Cookbook [3],1,1,67010
        ///0,400024A4,Nomadic Warrior&apos;s Cookbook [4],1,1,67800
        ///0,400024A7,Nomadic Warrior&apos;s Cookbook [5],1,1,67830
        ///0,40002456,Nomadic Warrior&apos;s Cookbook [6],1,1,67020
        ///0,40002459,Nomadic Warrior&apos;s Cookbook [7],1,1,67050
        ///0,400024AC,Nomadic Warrior&apos;s Cookbook [8],1,1,67880
        ///0,4000247F,Nomadic Warrior&apos;s Cookbook [9],1,1,67430
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cookbooks {
            get {
                return ResourceManager.GetString("Cookbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40005141,Aeonian Butterfly,999,999
        ///0,40003c3c,Albinauric Bloodclot,999,999
        ///0,400050c9,Altus Bloom,999,999
        ///0,400050d3,Arteria Leaf,999,999
        ///0,40003ab6,Beast Blood,999,999
        ///1,401ebf18,Beast Horn,999,999
        ///0,40003aa2,Beast Liver,999,999
        ///1,401ed2a6,Black Pyrefly,999,999
        ///1,401ed2bf,Blessed Bone Shard,999,999
        ///0,4000515f,Blood-Tainted Excrement,999,999
        ///0,400050f3,Bloodrose,999,999
        ///0,40005169,Budding Cave Moss,999,999
        ///0,40003aca,Budding Horn,999,999
        ///0,40005168,Cave Moss,999,999
        ///1,401ed2ba,Congealed Putr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CraftingMaterials {
            get {
                return ResourceManager.GetString("CraftingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,401eafaa,Bloodsucking Cracked Tear,1,1
        ///0,40002afc,Cerulean Crystal Tear,1,1
        ///0,40002afd,Cerulean Crystal Tear,1,1
        ///0,40002b11,Cerulean Hidden Tear,1,1
        ///1,401eaf96,Cerulean-Sapping Cracked Tear,1,1
        ///0,40002aff,Crimson Bubbletear,1,1
        ///0,40002afa,Crimson Crystal Tear,1,1
        ///0,40002afb,Crimson Crystal Tear,1,1
        ///1,401eaf8c,Crimson-Sapping Cracked Tear,1,1
        ///0,40002b01,Crimsonburst Crystal Tear,1,1
        ///1,401eaf82,Crimsonburst Dried Tear,1,1
        ///0,40002af8,Crimsonspill Crystal Tear,1,1
        ///0,40002b0c,Crimsonwhorl Bubbletea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CrystalTears {
            get {
                return ResourceManager.GetString("CrystalTears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 41 10             mov    rax,QWORD PTR [rcx+0x10]
        ///48 3b 05 00 00 00 00    cmp    rax,QWORD PTR [rip+0x0]        # c &lt;_main+0xc&gt;
        ///75 0b                   jne    19 &lt;skip&gt;
        ///58                      pop    rax
        ///48 89 5c 24 08          mov    QWORD PTR [rsp+0x8],rbx
        ///e9 00 00 00 00          jmp    19 &lt;skip&gt;
        ///000000000019 &lt;skip&gt;:
        ///58                      pop    rax
        ///30 c0                   xor    al,al
        ///c3                      ret.
        /// </summary>
        internal static string DisableAllExceptTarget {
            get {
                return ResourceManager.GetString("DisableAllExceptTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Nebula Hand Slam
        ///3,Spin Swing
        ///4,Straight Nebula
        ///5,Single Poke
        ///6,5 Hit Combo
        ///7,Wave of Gold
        ///8,Fire Breath
        ///10,Grab
        ///11,Swim Left Attack
        ///12,Swim Right Attack
        ///14,Standing Needles
        ///15,Stake Attack
        ///19,Fly Attack
        ///20,Nebula Swipe
        ///21,Nebula AoE
        ///30,Swim Needles
        ///31,Flying Needles.
        /// </summary>
        internal static string EbActs {
            get {
                return ResourceManager.GetString("EbActs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 e5                mov    rbp,rsp
        ///48 81 ec 98 05 00 00    sub    rsp,0x598
        ///48 8d 8d e0 fb ff ff    lea    rcx,[rbp-0x420]
        ///ba 00 00 00 00          mov    edx,0x0
        ///e8 00 00 00 00          call   1b &lt;_main+0x1b&gt;
        ///48 8d 8d c8 fb ff ff    lea    rcx,[rbp-0x438]
        ///48 8d 95 c8 fa ff ff    lea    rdx,[rbp-0x538]
        ///48 89 51 10             mov    QWORD PTR [rcx+0x10],rdx
        ///4c 8d 85 a8 fa ff ff    lea    r8,[rbp-0x558]
        ///4c 89 82 98 00 00 00    mov    QWORD PTR [rdx+0x98],r8
        ///49 89 50 18             mov    QWORD P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExecuteTalkCommand {
            get {
                return ResourceManager.GetString("ExecuteTalkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 7 &lt;_main+0x7&gt;
        ///75 39                   jne    42 &lt;normal&gt;
        ///81 78 28 00 00 00 00    cmp    DWORD PTR [rax+0x28],0x0
        ///75 30                   jne    42 &lt;normal&gt;
        ///52                      push   rdx
        ///41 50                   push   r8
        ///8b 15 00 00 00 00       mov    edx,DWORD PTR [rip+0x0]        # 1b &lt;_main+0x1b&gt;
        ///4c 8d 05 00 00 00 00    lea    r8,[rip+0x0]        # 22 &lt;_main+0x22&gt;
        ///41 8b 04 90             mov    eax,DWORD PTR [r8+rdx*4]
        ///ff c2      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForceActSequence {
            get {
                return ResourceManager.GetString("ForceActSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///88 01                   mov    BYTE PTR [rcx],al
        ///c3                      ret.
        /// </summary>
        internal static string GetEvent {
            get {
                return ResourceManager.GetString("GetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string GiveRunes {
            get {
                return ResourceManager.GetString("GiveRunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Roundtable Hold,Table of Lost Grace,11101950,71190
        ///0,Limgrave,The First Step,1042361951,76101
        ///0,Limgrave,Church of Elleh,1042361950,76100
        ///0,Limgrave,Gatefront,1042371950,76111
        ///0,Limgrave,Waypoint Ruins Cellar,1044361950,76120
        ///0,Limgrave,Artist&apos;s Shack,1044381950,76103
        ///0,Limgrave,Third Church of Marika,1046381950,76104
        ///0,Limgrave,Fort Haight West,1045361950,76105
        ///0,Limgrave,Agheel Lake South,1044351950,76106
        ///0,Limgrave,Agheel Lake North,1043371950,76108
        ///0,Limgrave,Church of Dragon Communion,10413 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Graces {
            get {
                return ResourceManager.GetString("Graces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 48 18             mov    rcx,QWORD PTR [rax+0x18]
        ///48 8b 50 08             mov    rdx,QWORD PTR [rax+0x8]
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string GraceWarp {
            get {
                return ResourceManager.GetString("GraceWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40001B59,Agheel&apos;s Flame,99,600
        ///0,40001B1C,Ancient Dragons&apos; Lightning Spear,99,600
        ///0,40001AFE,Ancient Dragons&apos; Lightning Strike,99,600
        ///1,401E9E84,Aspects of the Crucible: Bloom,99,600
        ///0,40001D60,Aspects of the Crucible: Breath,99,600
        ///0,40001D56,Aspects of the Crucible: Horns,99,600
        ///0,40001D4C,Aspects of the Crucible: Tail,99,600
        ///1,401E9E7A,Aspects of the Crucible: Thorns,99,600
        ///0,4000196E,Assassin&apos;s Approach,99,600
        ///0,400018BA,Barrier of Gold,99,600
        ///1,401E9FE2,Bayle&apos;s Flame Lightning,99,600
        ///1,401 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Incantations {
            get {
                return ResourceManager.GetString("Incantations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 3b 46 08             cmp    rax,QWORD PTR [rsi+0x8]
        ///75 0a                   jne    22 &lt;normal&gt;
        ///58                      pop    rax
        ///48 83 fe 00             cmp    rsi,0x0
        ///e9 00 00 00 00          jmp    22 &lt;normal&gt;
        ///000000000022 &lt;normal&gt;:
        ///58                      pop    rax
        ///80 bf 5f 02 00 00 00    cmp    BYTE PTR [rdi+0x25f],0x0
        ///e9 00 00 00 00          jm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfinitePoise {
            get {
                return ResourceManager.GetString("InfinitePoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # b &lt;_main+0xb&gt;
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 12 &lt;_main+0x12&gt;
        ///74 1d                   je     31 &lt;skip_quantity_adjust&gt;
        ///48 8d 4b 44             lea    rcx,[rbx+0x44]
        ///e8 00 00 00 00          call   1d &lt;_main+0x1d&gt;
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # 23 &lt;_main+0x23&gt;
        ///8b 53 48                mov    edx,DWORD PTR [rbx+0x48]
        ///01 c2                   add     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemSpawn {
            get {
                return ResourceManager.GetString("ItemSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///49 be 00 00 00 00 00    movabs r14,0x0
        ///00 00 00
        ///49 bf 00 00 00 00 00    movabs r15,0x0
        ///00 00 00
        ///49 8b 8f 08 e5 01 00    mov    rcx,QWORD PTR [r15+0x1e508]
        ///48 8b 01                mov    rax,QWORD PTR [rcx]
        ///ff 10                   call   QWORD PTR [rax]
        ///48 89 c6                mov    rsi,rax
        ///49 8b bf b8 f1 01 00    mov    rdi,QWORD PTR [r15+0x1f1b8]
        ///49 8b 9f c0 f1 01 00    mov    rbx,QWORD PTR [r15+0x1f1c0]
        ///000000000035 &lt;loop_start&gt;:
        ///48 39 df                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KillAll {
            get {
                return ResourceManager.GetString("KillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 8f 88 00 00 00    mov    rcx,QWORD PTR [rdi+0x88]
        ///48 89 05 00 00 00 00    mov    QWORD PTR [rip+0x0],rax        # e &lt;_main+0xe&gt;
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string LockedTarget {
            get {
                return ResourceManager.GetString("LockedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 3b 58 70             cmp    rbx,QWORD PTR [rax+0x70]
        ///75 03                   jne    22 &lt;normal&gt;
        ///0f 57 c0                xorps  xmm0,xmm0
        ///000000000022 &lt;normal&gt;:
        ///f3 0f 11 43 18          movss  DWORD PTR [rbx+0x18],xmm0
        ///58                      pop    rax
        ///e9 00 00 00 00          jmp    2d &lt;normal+0x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_InAirTimer {
            get {
                return ResourceManager.GetString("NoClip_InAirTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 f8 39             cmp    rax,0x39
        ///75 13                   jne    19 &lt;check_ctrl&gt;
        ///f6 84 08 e8 07 00 00    test   BYTE PTR [rax+rcx*1+0x7e8],0x80
        ///80
        ///76 09                   jbe    19 &lt;check_ctrl&gt;
        ///c6 05 00 00 00 00 02    mov    BYTE PTR [rip+0x0],0x2        # 17 &lt;_main+0x17&gt;
        ///eb 17                   jmp    30 &lt;xor_exit&gt;
        ///000000000019 &lt;check_ctrl&gt;:
        ///48 83 f8 1d             cmp    rax,0x1d
        ///75 1a                   jne    39 &lt;normal&gt;
        ///f6 84 08 e8 07 00 00    test   BYTE PTR [rax+rcx*1+0x7e8],0x80
        ///80
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Keyboard {
            get {
                return ResourceManager.GetString("NoClip_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 7c 24 36 4b          cmp    BYTE PTR [rsp+0x36],0x4b
        ///72 0e                   jb     15 &lt;check_up&gt;
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # e &lt;_main+0xe&gt;
        ///c6 44 24 36 00          mov    BYTE PTR [rsp+0x36],0x0
        ///eb 13                   jmp    28 &lt;exit&gt;
        ///000000000015 &lt;check_up&gt;:
        ///80 7c 24 37 4b          cmp    BYTE PTR [rsp+0x37],0x4b
        ///72 0c                   jb     28 &lt;exit&gt;
        ///c6 05 00 00 00 00 02    mov    BYTE PTR [rip+0x0],0x2        # 23 &lt;check_up+0xe&gt;
        ///c6 44 24 37 00          mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Triggers {
            get {
                return ResourceManager.GetString("NoClip_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 3b 58 68             cmp    rbx,QWORD PTR [rax+0x68]
        ///0f 85 14 01 00 00       jne    134 &lt;skip&gt;
        ///0f 10 43 70             movups xmm0,XMMWORD PTR [rbx+0x70]
        ///41 51                   push   r9
        ///41 50                   push   r8
        ///52                      push   rdx
        ///51            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_UpdateCoords {
            get {
                return ResourceManager.GetString("NoClip_UpdateCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,4000089A,Prattling Pate &quot;Apologies&quot;,1,600
        ///0,40000898,Prattling Pate &quot;Hello&quot;,1,600
        ///1,401E8CE6,Prattling Pate &quot;Lamentation&quot;,1,600
        ///0,4000089E,Prattling Pate &quot;Let&apos;s get to it&quot;,1,600
        ///0,4000089D,Prattling Pate &quot;My beloved&quot;,1,600
        ///0,4000089C,Prattling Pate &quot;Please help&quot;,1,600
        ///0,40000899,Prattling Pate &quot;Thank you&quot;,1,600
        ///0,4000089B,Prattling Pate &quot;Wonderful&quot;,1,600
        ///0,4000089F,Prattling Pate &quot;You&apos;re beautiful&quot;,1,600
        ///.
        /// </summary>
        internal static string PrattlingPate {
            get {
                return ResourceManager.GetString("PrattlingPate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///52                      push   rdx
        ///41 50                   push   r8
        ///41 51                   push   r9
        ///48 83 ec 70             sub    rsp,0x70
        ///0f 11 04 24             movups XMMWORD PTR [rsp],xmm0
        ///0f 11 4c 24 10          movups XMMWORD PTR [rsp+0x10],xmm1
        ///0f 11 54 24 20          movups XMMWORD PTR [rsp+0x20],xmm2
        ///0f 11 5c 24 30          movups XMMWORD PTR [rsp+0x30],xmm3
        ///0f 11 64 24 40          movups XMMWORD PTR [rsp+0x40],xmm4
        ///0f 11 6c 24 50          movups XMM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReduceTargetView {
            get {
                return ResourceManager.GetString("ReduceTargetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 49 08             mov    rcx,QWORD PTR [rcx+0x8]
        ///81 fa a5 2e 00 00       cmp    edx,0x2ea5
        ///75 03                   jne    f &lt;normal&gt;
        ///48 31 c9                xor    rcx,rcx
        ///00000000000f &lt;normal&gt;:
        ///48 85 c9                test   rcx,rcx
        ///e9 00 00 00 00          jmp    17 &lt;normal+0x8&gt;.
        /// </summary>
        internal static string RykardNoMega {
            get {
                return ResourceManager.GetString("RykardNoMega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 db                   xor    bl,bl
        ///0f 57 ff                xorps  xmm7,xmm7
        ///52                      push   rdx
        ///48 8b 15 00 00 00 00    mov    rdx,QWORD PTR [rip+0x0]        # d &lt;_main+0xd&gt;
        ///48 3b 96 e0 01 00 00    cmp    rdx,QWORD PTR [rsi+0x1e0]
        ///0f 85 d0 00 00 00       jne    ea &lt;normal&gt;
        ///51                      push   rcx
        ///53                      push   rbx
        ///50                      push   rax
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 23 &lt;_main+0x23&gt;
        ///8b 05 00 00 00 00       mov    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaveAttackInfo {
            get {
                return ResourceManager.GetString("SaveAttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 20             sub    rsp,0x20
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string SetEvent {
            get {
                return ResourceManager.GetString("SetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string SetSpEffect {
            get {
                return ResourceManager.GetString("SetSpEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,4000114F,Adula&apos;s Moonblade,99,600
        ///0,400011F8,Ambush Shard,99,600
        ///0,40001389,Ancient Death Rancor,99,600
        ///1,401E96DC,Blades of Stone,99,600
        ///0,4000132E,Briars of Punishment,99,600
        ///0,40001324,Briars of Sin,99,600
        ///0,40000FF0,Cannon of Haima,99,600
        ///0,4000114E,Carian Greatsword,99,600
        ///0,400010CD,Carian Phalanx,99,600
        ///0,40001162,Carian Piercer,99,600
        ///0,40001220,Carian Retaliation,99,600
        ///0,40001158,Carian Slicer,99,600
        ///1,401EA17C,Cherishing Fingers,99,600
        ///0,40001271,Collapsing Stars,99,600
        ///0,40000FB5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sorceries {
            get {
                return ResourceManager.GetString("Sorceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40033838,Albinauric Ashes,1,600
        ///0,40033068,Ancestral Follower Ashes,1,600
        ///1,4021CC58,Ancient Dragon Florissax,1,600
        ///0,4003E800,Ancient Dragon Knight Kristoff,1,600
        ///0,4003CCA8,Archer Ashes,1,600
        ///0,400372D0,Avionette Soldier Ashes,1,600
        ///0,40038270,Azula Beastman Ashes,1,600
        ///0,40031510,Banished Knight Engvall,1,600
        ///0,40031128,Banished Knight Oleg,1,600
        ///0,40035F48,Battlemage Hugues,1,600
        ///1,4021B8D0,Bigmouth Imp Ashes,1,600
        ///0,40030D40,Black Knife Tiche,1,600
        ///1,4021B4E8,Black Knight Captain Huw,1,60 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpiritAshes {
            get {
                return ResourceManager.GetString("SpiritAshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,200003e8,Crimson Amber Medallion,1,1
        ///0,200003e9,Crimson Amber Medallion +1,1,1
        ///0,200003ea,Crimson Amber Medallion +2,1,1
        ///0,200003f2,Cerulean Amber Medallion,1,1
        ///0,200003f3,Cerulean Amber Medallion +1,1,1
        ///0,200003f4,Cerulean Amber Medallion +2,1,1
        ///0,200003fc,Viridian Amber Medallion,1,1
        ///0,200003fd,Viridian Amber Medallion +1,1,1
        ///0,200003fe,Viridian Amber Medallion +2,1,1
        ///0,20000406,Arsenal Charm,1,1
        ///0,20000407,Arsenal Charm +1,1,1
        ///0,20000408,Great-Jar&apos;s Arsenal,1,1
        ///0,20000410,Erdtree&apos;s Favor,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Talismans {
            get {
                return ResourceManager.GetString("Talismans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 3b 47 08             cmp    rax,QWORD PTR [rdi+0x8]
        ///75 05                   jne    13 &lt;normal&gt;
        ///f3 0f 10 47 14          movss  xmm0,DWORD PTR [rdi+0x14]
        ///000000000013 &lt;normal&gt;:
        ///f3 0f 11 47 10          movss  DWORD PTR [rdi+0x10],xmm0
        ///58                      pop    rax
        ///e9 00 00 00 00          jmp    1e &lt;normal+0xb&gt;.
        /// </summary>
        internal static string TargetNoStagger {
            get {
                return ResourceManager.GetString("TargetNoStagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40002774,Smithing Stone [1],999,999
        ///0,40002775,Smithing Stone [2],999,999
        ///0,40002776,Smithing Stone [3],999,999
        ///0,40002777,Smithing Stone [4],999,999
        ///0,40002778,Smithing Stone [5],999,999
        ///0,40002779,Smithing Stone [6],999,999
        ///0,4000277A,Smithing Stone [7],999,999
        ///0,4000277B,Smithing Stone [8],999,999
        ///0,4000279C,Ancient Dragon Smithing Stone,999,999
        ///0,400027B0,Somber Smithing Stone [1],999,999
        ///0,400027B1,Somber Smithing Stone [2],999,999
        ///0,400027B2,Somber Smithing Stone [3],999,999
        ///0,400027B3,S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpgradeMaterials {
            get {
                return ResourceManager.GetString("UpgradeMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 10 05 00 00 00 00    movups xmm0,XMMWORD PTR [rip+0x0]        # 7 &lt;_main+0x7&gt;
        ///0f 11 80 a0 0a 00 00    movups XMMWORD PTR [rax+0xaa0],xmm0
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string WarpCoordWrite {
            get {
                return ResourceManager.GetString("WarpCoordWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b9 ff ff ff ff          mov    ecx,0xffffffff
        ///ba ff ff ff ff          mov    edx,0xffffffff
        ///41 b8 ff ff ff ff       mov    r8d,0xffffffff
        ///41 b9 ff ff ff ff       mov    r9d,0xffffffff
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string WarpToBlock {
            get {
                return ResourceManager.GetString("WarpToBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33200000,Academy Glintstone Staff,57,2,0
        ///3070000,Alabaster Lord&apos;s Sword,5,0,1
        ///41010000,Albinauric Bow,51,2,0
        ///31040000,Albinauric Shield,67,2,0
        ///33190000,Albinauric Staff,57,2,0
        ///4500000,Ancient Meteoric Ore Greatsword,7,0,1
        ///41510000,Ansbach&apos;s Longbow,51,0,1
        ///32220000,Ant&apos;s Skull Plate,69,0,1
        ///5040000,Antspur Rapier,15,2,0
        ///12510000,Anvil Hammer,41,0,1
        ///43080000,Arbalest,55,0,0
        ///33130000,Astrologer&apos;s Staff,57,2,0
        ///23050000,Axe of Godfrey,41,0,1
        ///15040000,Axe of Godrick,19,0,1
        ///33230000,Azur&apos;s Glintstone  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,65600,Upgrade - Standard,1,1
        ///0,65610,Iron Whetblade (Heavy),1,1
        ///0,65620,Iron Whetblade (Keen),1,1
        ///0,65630,Iron Whetblade (Quality),1,1
        ///0,65640,Red-Hot Whetblade (Fire),1,1
        ///0,65650,Red-Hot Whetblade (Flame Art),1,1
        ///0,65660,Sanctified Whetblade (Lightning),1,1
        ///0,65670,Sanctified Whetblade (Sacred),1,1
        ///0,65680,Glintstone Whetblade (Magic),1,1
        ///0,65690,Glintstone Whetblade (Frost),1,1
        ///0,65700,Black Whetblade (Poison),1,1
        ///0,65710,Black Whetblade (Blood),1,1
        ///0,65720,Black Whetblade (Occult),1,1
        ///.
        /// </summary>
        internal static string Whetblades {
            get {
                return ResourceManager.GetString("Whetblades", resourceCulture);
            }
        }
    }
}
