//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilkyRing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilkyRing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Roundtable Hold,Table of Lost Grace,11101950,71190
        ///0,Limgrave,The First Step,1042361951,76101
        ///0,Limgrave,Church of Elleh,1042361950,76100
        ///0,Limgrave,Gatefront,1042371950,76111
        ///0,Limgrave,Waypoint Ruins Cellar,1044361950,76120
        ///0,Limgrave,Artist&apos;s Shack,1044381950,76103
        ///0,Limgrave,Third Church of Marika,1046381950,76104
        ///0,Limgrave,Fort Haight West,1045361950,76105
        ///0,Limgrave,Agheel Lake South,1044351950,76106
        ///0,Limgrave,Agheel Lake North,1043371950,76108
        ///0,Limgrave,Church of Dragon Communion,10413 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Graces {
            get {
                return ResourceManager.GetString("Graces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 48 18             mov    rcx,QWORD PTR [rax+0x18]
        ///48 8b 50 08             mov    rdx,QWORD PTR [rax+0x8]
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string GraceWarp {
            get {
                return ResourceManager.GetString("GraceWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 8f 88 00 00 00    mov    rcx,QWORD PTR [rdi+0x88]
        ///48 89 05 00 00 00 00    mov    QWORD PTR [rip+0x0],rax        # e &lt;_main+0xe&gt;
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string LockedTarget {
            get {
                return ResourceManager.GetString("LockedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 3b 58 70             cmp    rbx,QWORD PTR [rax+0x70]
        ///75 03                   jne    22 &lt;normal&gt;
        ///0f 57 c0                xorps  xmm0,xmm0
        ///000000000022 &lt;normal&gt;:
        ///f3 0f 11 43 18          movss  DWORD PTR [rbx+0x18],xmm0
        ///58                      pop    rax
        ///e9 00 00 00 00          jmp    2d &lt;normal+0x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_InAirTimer {
            get {
                return ResourceManager.GetString("NoClip_InAirTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 f8 39             cmp    rax,0x39
        ///75 13                   jne    19 &lt;check_ctrl&gt;
        ///f6 84 08 e8 07 00 00    test   BYTE PTR [rax+rcx*1+0x7e8],0x80
        ///80
        ///76 09                   jbe    19 &lt;check_ctrl&gt;
        ///c6 05 00 00 00 00 02    mov    BYTE PTR [rip+0x0],0x2        # 17 &lt;_main+0x17&gt;
        ///eb 17                   jmp    30 &lt;xor_exit&gt;
        ///000000000019 &lt;check_ctrl&gt;:
        ///48 83 f8 1d             cmp    rax,0x1d
        ///75 1a                   jne    39 &lt;normal&gt;
        ///f6 84 08 e8 07 00 00    test   BYTE PTR [rax+rcx*1+0x7e8],0x80
        ///80
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Keyboard {
            get {
                return ResourceManager.GetString("NoClip_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 7c 24 36 4b          cmp    BYTE PTR [rsp+0x36],0x4b
        ///72 0e                   jb     15 &lt;check_up&gt;
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # e &lt;_main+0xe&gt;
        ///c6 44 24 36 00          mov    BYTE PTR [rsp+0x36],0x0
        ///eb 13                   jmp    28 &lt;exit&gt;
        ///000000000015 &lt;check_up&gt;:
        ///80 7c 24 37 4b          cmp    BYTE PTR [rsp+0x37],0x4b
        ///72 0c                   jb     28 &lt;exit&gt;
        ///c6 05 00 00 00 00 02    mov    BYTE PTR [rip+0x0],0x2        # 23 &lt;check_up+0xe&gt;
        ///c6 44 24 37 00          mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Triggers {
            get {
                return ResourceManager.GetString("NoClip_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 3b 58 68             cmp    rbx,QWORD PTR [rax+0x68]
        ///0f 85 d3 00 00 00       jne    f6 &lt;skip&gt;
        ///0f 10 43 70             movups xmm0,XMMWORD PTR [rbx+0x70]
        ///41 50                   push   r8
        ///52                      push   rdx
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 80 08 e5 01 00   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_UpdateCoords {
            get {
                return ResourceManager.GetString("NoClip_UpdateCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///52                      push   rdx
        ///41 50                   push   r8
        ///41 51                   push   r9
        ///48 83 ec 70             sub    rsp,0x70
        ///0f 11 04 24             movups XMMWORD PTR [rsp],xmm0
        ///0f 11 4c 24 10          movups XMMWORD PTR [rsp+0x10],xmm1
        ///0f 11 54 24 20          movups XMMWORD PTR [rsp+0x20],xmm2
        ///0f 11 5c 24 30          movups XMMWORD PTR [rsp+0x30],xmm3
        ///0f 11 64 24 40          movups XMMWORD PTR [rsp+0x40],xmm4
        ///0f 11 6c 24 50          movups XMM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReduceTargetView {
            get {
                return ResourceManager.GetString("ReduceTargetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 49 08             mov    rcx,QWORD PTR [rcx+0x8]
        ///81 fa a5 2e 00 00       cmp    edx,0x2ea5
        ///75 03                   jne    f &lt;normal&gt;
        ///48 31 c9                xor    rcx,rcx
        ///00000000000f &lt;normal&gt;:
        ///48 85 c9                test   rcx,rcx
        ///e9 00 00 00 00          jmp    17 &lt;normal+0x8&gt;.
        /// </summary>
        internal static string RykardNoMega {
            get {
                return ResourceManager.GetString("RykardNoMega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 20             sub    rsp,0x20
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///49 b8 00 00 00 00 00    movabs r8,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string SetEvent {
            get {
                return ResourceManager.GetString("SetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string SetSpEffect {
            get {
                return ResourceManager.GetString("SetSpEffect", resourceCulture);
            }
        }
    }
}
